plugins=(git, github, git-remote-branch, osx)

source $ZSH/oh-my-zsh.sh

export GIT_MERGE_AUTOEDIT=no
source /usr/share/autojump/autojump.sh
bindkey \^U backward-kill-line
unsetopt histverify
alias 'rm'='mv --verbose -f --backup=numbered --target-directory ~/.trash'
alias 'squash'='/bin/rm -rf ~/.trash/*'

if [[ "$TERM" != "screen" ]]; then
    # Attempt to discover a detached session and attach 
    # it, else create a new session

    WHOAMI=$(whoami)
    if tmux has-session -t $WHOAMI 2>/dev/null; then
        tmux -2 attach-session -t $WHOAMI
    else
        tmux -2 new-session -s $WHOAMI
    fi
fi
