plugins=(git github macos)

source $ZSH/oh-my-zsh.sh

export GIT_MERGE_AUTOEDIT=no
bindkey \^U backward-kill-line
unsetopt histverify
alias 'rm'='mv --verbose -f --backup=numbered --target-directory ~/.trash'
alias 'squash'='/bin/rm -rf ~/.trash/*'
alias '..'='cd ..'
alias '...'='cd ../..'
autoload -U compinit && compinit -u

function goto() {
    PYPATH=$(py-module-path $1)
    echo $PYPATH
    if [ -d $PYPATH ];then
        cd $PYPATH
    fi
}
